import com.panayotis.gnuplot.JavaPlot;
import com.panayotis.gnuplot.plot.FunctionPlot;
import com.panayotis.gnuplot.terminal.ImageTerminal;
import com.panayotis.gnuplot.terminal.PostscriptTerminal;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
/*
 * test.java
 *
 * Created on October 17, 2007, 3:15 AM
 */

/**
 *
 * @author  teras
 */
public class test extends JFrame {
    
    public static void main(String [] args) {
        
        ImageTerminal png = new ImageTerminal();
        PostscriptTerminal eps = new PostscriptTerminal(System.getProperty("user.home")+
                System.getProperty("file.separator")+"output.eps");
        
        JavaPlot p = new JavaPlot();
        //    p.getDebugger().setLevel(Debug.WARNING);
        
        p.setTitle("Big Fat Title");
        p.getAxis("x").setLogScale(true);
        p.getAxis("x").setLabel("X axis", "Arial", 30);
        p.getAxis("y").setLabel("Y axis");
        
        p.setBoundaries(1, 100);
        p.setKey(JavaPlot.Key.TOP_RIGHT);
        
        double [][] plot = { {1, 1.1}, {2, 2.2}, {3, 3.3}, {4, 4.3} };
        p.addPlot(plot);
        
       // p.addPlot("sin(x*x)-cos(sqrt(x))");
        FunctionPlot fp = new FunctionPlot("0");
        fp.set("with", "points");
        p.addPlot(fp);

        png.set("large");
        
        p.setTerminal(png);
     //   p.plot();
//        p.setTerminal(eps);
  //      p.setPointSize(4);  
        p.getPreInit().add("plot x");
          p.plot();
        
        BufferedImage img = png.getImage();
        test f = new test(img);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }
    
    
    /**
     * Creates new form test
     */
    public test(BufferedImage img) {
        initComponents();
        if (img==null) return;
        pic.setIcon(new ImageIcon(img));
        pic.setSize(img.getWidth(), img.getHeight());
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pic.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(pic, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pic;
    // End of variables declaration//GEN-END:variables
    
}
